spring.application.name=user-service-test
server.port=0

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.cache.type=redis
spring.cache.redis.time-to-live=30m
spring.cache.redis.cache-null-values=false