spring.application.name=user-service
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${APP_USER}
spring.datasource.password=${APP_USER_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.data.redis.host=${REDIS.HOST}
spring.data.redis.port=${REDIS_PORT}
spring.cache.type=redis
spring.cache.redis.time-to-live=30m
spring.cache.redis.cache-null-values=false

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${RESOURCE_SERVER_JWK_SET_URI}
logging.level.org.springframework.security=TRACE