#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
CREATE USER ${APP_USER} WITH PASSWORD '${APP_USER_PASSWORD}';

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_USER};

GRANT USAGE, CREATE ON SCHEMA public TO ${APP_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${APP_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${APP_USER} IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${APP_USER} IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${APP_USER};
EOSQL